spring.application.name=enrollment-service
server.port=${PORT:9092}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/learnsphere_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
course.service.base-url=${COURSE_SERVICE_URL:http://${COURSE_SERVICE_HOSTPORT:localhost:9091}}

# Razorpay
razorpay.key=${RAZORPAY_KEY_ID}
razorpay.secret=${RAZORPAY_KEY_SECRET}


jwt.secret=${JWT_SECRET:learnsphere-super-secure-jwt-secret-key-2026-project-auth-service}
jwt.expiration=86400000

# Disable default generated Spring Security user/password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ================= ACTUATOR (KEEP-ALIVE) =================
management.endpoints.web.base-path=/api/enrollments/actuator
management.endpoints.web.exposure.include=health
management.health.defaults.enabled=false
management.health.ping.enabled=true
