spring.application.name=enrollment-service
server.port=9092
spring.datasource.url=jdbc:mysql://localhost:3306/learnsphere_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
course.service.base-url=http://localhost:9091

# Razorpay
razorpay.key=rzp_test_SIf0T7lHEketYm
razorpay.secret=JgemT4toZRQuaFv871NGjnDv


jwt.secret=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service
jwt.expiration=86400000

# Disable default generated Spring Security user/password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
