server.port=${PORT:9094}
spring.application.name=discussion-notification-service

spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/learnsphere_forum_db}
spring.data.mongodb.auto-index-creation=true

jwt.secret=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service

forum.course-service.base-url=${COURSE_SERVICE_URL:http://${COURSE_SERVICE_HOSTPORT:localhost:9091}}
