server.port=9094
spring.application.name=discussion-notification-service

spring.data.mongodb.uri=mongodb://localhost:27017/learnsphere_forum_db
spring.data.mongodb.auto-index-creation=true

jwt.secret=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service

forum.course-service.base-url=http://localhost:9091
