server.port=8085

spring.application.name=learning-progress-service

spring.data.mongodb.uri=mongodb://localhost:27017/lms_learning_db

jwt.secret=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service
