# ===============================
# SERVER
# ===============================
server.port=8081

spring.application.name=API-GATEWAY

# ===============================
# EUREKA CLIENT
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# GATEWAY DISCOVERY ROUTING
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# ACTUATOR (optional)
# ===============================
management.endpoints.web.exposure.include=*
