spring.application.name=learn-progress-service
server.port=${PORT:9093}
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/learnsphere_db}
spring.data.mongodb.auto-index-creation=false
course.service.base-url=${COURSE_SERVICE_URL:http://${COURSE_SERVICE_HOSTPORT:localhost:9091}}
enrollment.service.base-url=${ENROLLMENT_SERVICE_URL:http://${ENROLLMENT_SERVICE_HOSTPORT:localhost:9092}}
discussion.notification.events.base-url=${DISCUSSION_SERVICE_URL:http://${DISCUSSION_SERVICE_HOSTPORT:localhost:9094}}
admin.analytics.events.base-url=${ADMIN_ANALYTICS_SERVICE_URL:http://${ADMIN_ANALYTICS_SERVICE_HOSTPORT:localhost:9095}}

# JWT validation (Resource Server)
spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET:learnsphere-super-secure-jwt-secret-key-2026-project-auth-service}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

spring.security.user.name=disabled
spring.security.user.password=disabled

# ================= ACTUATOR (KEEP-ALIVE) =================
management.endpoints.web.exposure.include=health
management.health.defaults.enabled=false
management.health.ping.enabled=true
