spring.application.name=learn-progress-service
server.port=9093
spring.data.mongodb.uri=mongodb://localhost:27017/learnsphere_db

course.service.base-url=http://localhost:9091
enrollment.service.base-url=http://localhost:9092
discussion.notification.events.base-url=http://localhost:9094
admin.analytics.events.base-url=http://localhost:9095

# JWT validation (Resource Server)
spring.security.oauth2.resourceserver.jwt.secret-key=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

spring.security.user.name=disabled
spring.security.user.password=disabled
