spring.application.name=course-service

spring.data.mongodb.uri=mongodb://localhost:27017/learnsphere_db
spring.data.mongodb.auto-index-creation=true

server.port=9091

jwt.secret=learnsphere-super-secure-jwt-secret-key-2026-project-auth-service
jwt.expiration=86400000