server.port=9095

spring.application.name=admin-analytics-service

spring.datasource.url=jdbc:mysql://localhost:3306/learnsphere_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable default generated Spring Security user/password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
