server.port=9095

spring.application.name=admin-analytics-service

spring.datasource.url=jdbc:mysql://localhost:3306/learnsphere_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable default generated Spring Security user/password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a2ea2a001@smtp-brevo.com
spring.mail.password=bsk833oPfGRFfQz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
app.mail.from=Vishnu <learnspheredemo@gmail.com>
